### ISSUE TITLE
LocalStorage vs node-localStorage

### ISSUE THREAD

**Issue by spyalert01** [lmaccherone/node-localstorage#14]
Hi,
What is the different between the normal HTML5 localStorage and node-localStorage?

**Comment by lmaccherone** [comment]
HTML5 localStorage is only available in the browser. node-localStorage runs in node.js. It implements most of the API. It does not support associative array index syntax but other than that it behaves just like the browser equivalent. 

Does that answer your question?

**Comment by spyalert01** [comment]
Thanks. 
I tested it, it actually created a folder in the server (./scratch)... once this is created, if other user is using the same server from different browser, the localstorage is accessible by other user.

I thought the original idea of localStorage should be it is in the Client Browser, rather than a folder in the Server?

**Comment by lmaccherone** [comment]
True that. 

There are two main use cases for node-localstorage: 1) headless testing of code that is intended to run in the browser; and 2) writing code that will run on either the server or the browser. I personally use it for caching. My MRU caching code sits on top of the localStorage API. When it's running in the browser, it uses the native localStorage. When it's running on the server, it uses node-localstorage. The point is that I only need to write my caching code once and it works in multiple places. Some folks refer to this as [isomorphic javascript](http://isomorphic.net/).

You wrote, "if other user is using the same server from different browser, the localstorage is accessible by other user." Note, you can control the directory used for each instance of node-localstorage and you can have as many of these instances as you wish. One strategy for keeping your user's data separate would be to create a separate instance for each user. But keep in mind, you have complete control over the server. You could write your server code such that everyone's data was in one database but only allowed the user to edit/view data if they had the appropriate permissions. Every online service you use on a daily basis (Facebook, Amazon, etc.) all take this approach when storing your data on their servers.

Note, node-localstorage has [7500 npm downloads per month](https://www.npmjs.com/package/node-localstorage) and [3 dozen published npm packages depend upon it](https://www.npmjs.com/browse/depended/node-localstorage). So, there are many others who have found a use for it. What programming need caused you to look at it in the first place?... or are you just curious about it?

**Comment by spyalert01** [comment]
I would like to use localStorage to keep my client WebToken.
And "in some way" pass the token back to server, for token authenthication. subsequently, pass this token to GraphQL for some other usage purposes

**Comment by lmaccherone** [comment]
It sounds like you could receive it on the server via the API you build and store it in memory for the length of the transaction. It doesn't sound like a server-side node-localstorage would help you.
