### ISSUE TITLE
Support optional persistence.

### ISSUE THREAD

**Issue by knpwrs** [lmaccherone/node-localstorage#15]
I think having the option of not persisting data would be helpful. I just need this for running unit-tests where data shouldn't persist past the current run.

**Comment by lmaccherone** [comment]
There is a method for deleting the folder created `_deleteLocation()`. 

However, an in-memory only storage option might be nice. I'll look at how hard that might be to add.

**Comment by KenPowers** [comment]
Perhaps a generic storage provider interface.

**Comment by lmaccherone** [comment]
I took a look and it will be more than just a little work to implement an in-memory option. I propose that if no directory is provided when it's instantiated, that it default to in-memory storage. I don't have time to do it just now, but maybe in the next week or so. Of course, if you do it yourself before then, I'll gladly accept  a well coded and tested pull request.

A generic storage provider interface is a lot more work than even just adding an in-memory option. Again, I'd welcome a well coded and tested pull request for this if you're up for it.

**Comment by nickcolley** [comment]
https://github.com/gr2m/localstorage-memory might work for your usecase?

**Comment by KenPowers** [comment]
@nickcolley That looks nice but optional persistence would still be awesome.

**Comment by Luminess** [comment]
It only requires a miniscule amount of work if [mock-fs](https://github.com/tschaub/mock-fs) is used. You [literally just require mock-fs in place of NodeJS's fs module](https://github.com/tschaub/mock-fs#creating-a-new-fs-module-instead-of-modifying-the-original) and ensure [the sole dependency of this project](https://github.com/npm/write-file-atomic) follows suit.

**Comment by lmaccherone** [comment]
That is a good option. I'm using npm package `write-file-atomic` for writes but that's only in one spot in the code and I could easily just check a conditional and use `mock-fs` for that whenever it's in-memory mode. I'll put it on the list to try in the next week... unless you want to submit a pull request. ;-)

**Comment by lmaccherone** [comment]
@LuminescentMoon 's idea is a really simple way to accomplish this. Anyone want to implement it and submit a pull request?

**Comment by lmaccherone** [comment]
I would still love to do this if someone needs it.

**Comment by trasherdk** [comment]
Well, #76 would need something. I was thinking MySQL / Redis maybe combined with [BroadcastChannel](https://github.com/pubkey/broadcast-channel)

**Comment by lmaccherone** [comment]
Closing due to lack of interest
