### ISSUE TITLE
probable regression

### ISSUE THREAD

**Issue by evilaliv3** [lmaccherone/node-localstorage#17]
hey @lmaccherone can you please look at this possible regression?

in openpgpj we were using node-localstorage since version 0.3.4 doing this:

```js
    localStorage1 = new LocalStorage('WTF');
    localStorage2 = new LocalStorage('WTF');

    localStorage1.setItem("wtf", "mumble");

    console.log(localStorage1.getItem('wtf'));
    console.log(localStorage2.getItem('wtf'));
```

the result of the above code at the time of 0.3.4 was to re-findind in localstorage2 the element written using localstorage1 object; this seems to not happen in the latest version.

thanks you so much

**Comment by lmaccherone** [comment]
It's very possible. I did a pretty serious refactoring to implement associative array syntax last week and your example is not in my tests. I'll take a look at it this weekend.

**Comment by evilaliv3** [comment]
i see.

anyway from what i've seen this regression exist since 0.6.0 or even from before.

**Comment by lmaccherone** [comment]
Ohh, then it's not from my work last week. I'll add your example as a test case to duplicate the problem and fix it anyway. Thanks for the extra info. It may end up saving me some time. :-)

**Comment by lmaccherone** [comment]
Fixed in v1.1.2 by using a Singleton-ish pattern.

**Comment by evilaliv3** [comment]
aside most people dislike them we love singletons pattern today cause it fixed node-localstorage! ;)

thank you @lmaccherone!

**Comment by evilaliv3** [comment]
the patch works @lmaccherone ! thanks!
