### ISSUE TITLE
es6 dynamic import is not supported

### ISSUE THREAD

**Issue by 5punk** [lmaccherone/node-localstorage#21]
I am writing an isomorphic app, which doesn't allow conditional imports.

If i go ahead and import it anyway I get an error

```
graceful-fs.js: Uncaught TypeError: Cannot read property 'prototype' of undefined
```

Any help?

**Comment by lmaccherone** [comment]
No sure how to deal with that. Are there other packages that you know of that work in both places without conditional imports? Maybe I could sense if window.LocalStorage already existed and if so, return that in my constructor. Can you modify it and try that to see if that works?

**Comment by edrpls** [comment]
Sorry for digging this up, but I am using it like this with no errors:

`import { LocalStorage } from 'node-localstorage';`
