### ISSUE TITLE
How much storage space is available

### ISSUE THREAD

**Issue by isvaljek** [lmaccherone/node-localstorage#22]
How much storage space is available and how persistant the data is?

**Comment by lmaccherone** [comment]
You can set the max number of bytes as the second parameter when instantiating:

     ls = new LocalStorage('./scratch2', 3000);

The data is stored in files in the directory specified by the first parameter. Care is taken to make sure that transactions are atomic so I think it's about as reliable as most browser implementations, as durable as your file system, and a bit more flexible than browser implementations. Note, this only works on node.js.

I have some folks using it as a primary data store and I also use the included wrapper, [JSONStorage](https://github.com/lmaccherone/node-localstorage/blob/master/test/JSONStorageTest.coffee), myself in a few projects where queries are not necessary.

That said, its primary usage is for testing code in node.js that you intend to run in the browser.
