### ISSUE TITLE
Atomic Writes Fails

### ISSUE THREAD

**Issue by anywhichway** [lmaccherone/node-localstorage#23]
On Windows, atomic writes sometimes fail due to hard to manage file ownership issues. An EPERM error is thrown on attempts to rename. Wrapping the write operation in `setItem` with a try catch block solves the problem, at the cost of the atomic operation:

```
try {
          writeSync(filename, valueString, 'utf8');
      } catch(e) {
          fs.writeFileSync(filename, valueString, 'utf8'); // above frequently fails on Windows, so try normal write
      }
```

**Comment by lmaccherone** [comment]
Thanks for the heads up. Any chance you could submit a pull request with this fix?

**Comment by anywhichway** [comment]
Sure, it will take a couple of days, busy on some other stuff. However, perhaps the fix ought to be done on the atomic write package itself? I am not really sure what causes the issue, it could be than rename behaves differently on Unix/Linux than Windows. My take on the atomic write code is that the write file function always tries to rename from the temp file created to ensure a full write to the original file but that rename often fails on Windows 10 when the original target already exists. I have Googled a read a lots of posts related to EPERM and rename but can't seem to find a fix that would work. Thoughts before I create a pull request on your code base?
