### ISSUE TITLE
calling setItem() in renderer process fail which use Angular 1.4.

### ISSUE THREAD

**Issue by zwangwang** [lmaccherone/node-localstorage#28]
Hi,
I am using it in electron project.

here's my main.js code.
require('include-path')(__dirname);
global.basePath = __dirname + '/';

// Set application data as global variable
try {
  global.userdataPath = app.getPath('appData') + '/TalkEnglish/';

  console.log("############### : " + global.userdataPath);
} catch (e) {
  console.error('### :' + e)
}

const ipcPlusM = require('./modules/electron-ipc-plus/index.js');
var talkProtocol = require('./modules/talk-protocol.js');

var JSONStorage = require('node-localstorage').JSONStorage;
var storageLocation = app.getPath('appData') + "/TalkEnglish";
global.nodeStorage = new JSONStorage(storageLocation);

and in my index.html file I call setItem() function, and it works when I call it out of Angular controller function, but it fails when I call in controller scope function.
but exceptionally getItem() works. I don't know why.
---------------------
				$scope.initUI = function() {
					var downStat = remote.getGlobal('nodeStorage').getItem('down_status');
					var stepStat = remote.getGlobal('nodeStorage').getItem('step_status');
					**remote.getGlobal('nodeStorage').setItem('step_status', '3');** // This line cause error
					if (('' + stepStat) !== 'null') {
						switch(stepStat) {
							case '3':
							$scope.goStep3();
							break;
							case '4':
							$scope.goStep4();
							break;
						}
					}
				}

				$scope.initUI();

---------------------
Here's the error.
![wx20170504-100002](https://cloud.githubusercontent.com/assets/17186283/25688301/7c5fd782-30b0-11e7-8c72-a9c7c7ed6705.png)

**Comment by lmaccherone** [comment]
My first guess is that the problem has something to do with the `write-file-atomic` package. You can prove this out by replacing the line near the top `writeSync = require('write-file-atomic').sync` with `writeSync = fs.writeFileSync`.

If the problem goes away when you try that, then I'll try to add a flag to the instantiation that will do that substitution for you.

**Comment by lmaccherone** [comment]
Were you able to get this working?
