### ISSUE TITLE
Maybe the `projectFilesBackup` directory could be deleted from npm package?

### ISSUE THREAD

**Issue by dickeylth** [lmaccherone/node-localstorage#29]
```
node-localstorage ➤ tree -L 4 -I node_modules                                                                                                                      git:master*
.
├── Cakefile
├── LocalStorage.js
├── README.md
├── package.json
├── projectFilesBackup
└── test
    └── test.html

2 directories, 5 files
```

As far as I know, the `projectFilesBackup` directory is generated by WebStorm upgrade, which could be deleted before being published to npm package.

**Comment by lmaccherone** [comment]
I don't want to push a new version just for this, but I've removed that folder from the source tree and when I increment the version, npm will be fixed. OK?

**Comment by dickeylth** [comment]
OK~
