### ISSUE TITLE
push tag 1.3.1 to github?

### ISSUE THREAD

**Issue by Kilian** [lmaccherone/node-localstorage#33]
I am running into the #23 issue and see that it's fixed in master, but it's not in any of the github releases. The github releases only go to 1.3.0 and do not contain that commit. NPM has version 1.3.1 but it's not easy to see which commits that includes. Can you push the tags to github too?

**Comment by lmaccherone** [comment]
I don't know how that happened because my publish script automatically adds the git tags upon successful push to npm. Maybe the script is failing somehow between those two steps. I will investigate. In the mean time, I manually pushed a new tag. Thanks for the heads up!
