### ISSUE TITLE
ERROR in ./node_modules/graceful-fs/graceful-fs.js

### ISSUE THREAD

**Issue by manish4781** [lmaccherone/node-localstorage#35]
this is my component code which us rendered on server side

```
import React, { Component } from 'react';
import Helmet from 'react-helmet';

export default class Kumar extends Component {
  constructor(props){
    super(props);
	if (typeof localStorage === "undefined" || localStorage === null) {
		require('fs');
	  var LocalStorage = require('node-localstorage').LocalStorage;
	  localStorage = new LocalStorage('./scratch');
	}

	localStorage.setItem('myFirstKey', 'myFirstValue');
	console.log(localStorage.getItem('myFirstKey'));
	console.log("inside local storage");
  }
    render() {
        return (
            <div>
                <h1>Welcome to React</h1>              
            </div>
        );
    }
}
```
Getting error
```
 ERROR in ./node_modules/graceful-fs/graceful-fs.js
    Module not found: Error: Can't resolve 'fs' in '/Users/Documents/master/xxx/node_modules/graceful-fs'
     @ ./node_modules/graceful-fs/graceful-fs.js 1:9-22
     @ ./node_modules/write-file-atomic/index.js
```
Am i using it correctly? i am rendering this component on server and same component will re-used in client side, when run in client, data should be stored on browser localstorage.

**Comment by lmaccherone** [comment]
I'm guessing that while you think it's being rendered server-side, this error is coming from a browser-side example. I suspect that using server-side for LocalStorage in React will not behave the way you expect anyway. For instance, once control is handed to the browser, anything saved server-side will not be available.

**Comment by manish4781** [comment]
@lmaccherone thanks for the quick reply, would you be able to help me on, how do i handle the scenario where my components are on server side rendering and same code is re-used for client side and i have to store some value in Local storage on my component code, but when server runs my code Window is not available.

**Comment by brunopontes-hotmart** [comment]
I've added `node = { fs: 'empty'}` to my webpack config file and it worked!

**Comment by lmaccherone** [comment]
@brunopontes-hotmart Thanks!!! Closing this issue. I can reopen if @manish4781 reports that it doesn't fix it in his context.

**Comment by yatin-anilabsinc** [comment]
> I've added `node = { fs: 'empty'}` to my webpack config file and it worked!

Hey can you tell me how you added this in ur webpack config file or if possible could you please share your webpack config file
