### ISSUE TITLE
`register` entry

### ISSUE THREAD

**Issue by dy** [lmaccherone/node-localstorage#42]
Sometimes it is handy to run node with some browser stuff polyfilled, for example

`node -r raf/polyfill -r browser-env/register test.js`

Would you consider adding `node-localstorage/register` entry to polyfill localStorage for node as well, similar to [browser-env/register](https://github.com/lukechilds/browser-env/blob/master/register.js)?

@lmaccherone

**Comment by lmaccherone** [comment]
I'm not familiar with this but if you submit a pull request, I will take a look.

**Comment by dy** [comment]
@lmaccherone sure https://github.com/lmaccherone/node-localstorage/pull/43
