### ISSUE TITLE
Can't resolve 'fs' in

### ISSUE THREAD

**Issue by ohari5336** [lmaccherone/node-localstorage#45]
`ERROR in ./node_modules/graceful-fs/graceful-fs.js
Module not found: Error: Can't resolve 'fs' in 'E:\experiments\wha experiments\WhatsAllApp-master\node_modules\graceful-fs'
 @ ./node_modules/graceful-fs/graceful-fs.js 1:9-22
 @ ./node_modules/node-localstorage/node_modules/write-file-atomic/index.js
 @ ./node_modules/node-localstorage/LocalStorage.js
 @ ./src/pack/Components/MainContent.js
 @ ./src/pack/Components/OverlayContainer.js
 @ ./src/pack/AppContainer.js
 @ ./src/index.js

ERROR in ./node_modules/node-localstorage/LocalStorage.js
Module not found: Error: Can't resolve 'fs' in 'E:\experiments\wha experiments\WhatsAllApp-master\node_modules\node-localstorage'
 @ ./node_modules/node-localstorage/LocalStorage.js 9:7-20
 @ ./src/pack/Components/MainContent.js
 @ ./src/pack/Components/OverlayContainer.js
 @ ./src/pack/AppContainer.js
 @ ./src/index.js`

this error show when i run `npx webpack`

**Comment by lmaccherone** [comment]
What version of node-localstorage? I just did a major update last night and wonder if that caused the problem.

**Comment by ohari5336** [comment]
I just type `npm install node-localstorage` today and use when I first compile my project I see this error

**Comment by lmaccherone** [comment]
‘npm ls node-localstorage’ will get you the version. However, I now suspect it has nothing to do with yesterday’s upgrade but rather you are webpack’ing for a browser while node-localstorage is designed to only run in node. If you can share a repo that duplicates the problem I can take a look.

**Comment by ohari5336** [comment]
`E:\experiments\wha experiments\WhatsAllApp-master>npm ls node-localstorage
whats_all_app_community_edition@0.0.1 E:\experiments\wha experiments\WhatsAllApp-master
`-- node-localstorage@2.1.4`

and my project is: https://github.com/ohari5336/WhatsAllApp-Mod

**Comment by lmaccherone** [comment]
Would you do me a favor and `npm uninstall node-localstorage` then reinstall with `npm install nodelocalstorage@1`

If you have the same problem, that will rule out the changes I did yesterday as the cause.

**Comment by lmaccherone** [comment]
Your repo looks like it's browser-only. Why do you even need node-localstorage? Why not just use the browser built-in window.localStorage that node-localstorage was built to emulate?

**Comment by lmaccherone** [comment]
ping. If you have figured this out or if you are now convinced it's not related to this project, just let me know or close the issue.

**Comment by ohari5336** [comment]
I solve my issue. thanks for giving attention and time for this

**Comment by mateja176** [comment]
> I solve my issue. thanks for giving attention and time for this

Let me guess, you removed the package entirely.
