### ISSUE TITLE
empty key

### ISSUE THREAD

**Issue by appy-one** [lmaccherone/node-localstorage#46]
When storing a value with an empty key, it is persisted as "---.EMPTY_STRING.---". When iterating through the keys using .length and .key(i), a key with name "---.EMPTY_STRING.---" is returned instead of "".

`let localStorage = new LocalStorage("./scratch");
localStorage.setItem("", "my value");
let key = localStorage.key(0); //  "---.EMPTY_STRING.---"`

**Comment by lmaccherone** [comment]
Good catch and pretty easy to fix. I'll try to work on it today.

**Comment by lmaccherone** [comment]
Fixed and published. It was even easier than I thought.
