### ISSUE TITLE
How to use listener?

### ISSUE THREAD

**Issue by enriquepiatti** [lmaccherone/node-localstorage#48]
Hi, can you provide some example using the event listeners?
Thanks !!

**Comment by enriquepiatti** [comment]
OK, this works:
```
localStorage.on('storage', function(e){
        const key = e.key;
        const newValue = e.newValue;
        const oldValue = e.oldValue;
    });
```

**Comment by lmaccherone** [comment]
I see that you got it working on your own, but I'm curious if the way it worked was not the same way as the native LocalStorage or somehow was not as expected?
