### ISSUE TITLE
Async get and set

### ISSUE THREAD

**Issue by enriquepiatti** [lmaccherone/node-localstorage#49]
Would be nice to have async functions for get and set.

**Comment by lmaccherone** [comment]
Is this supported by the latest versions of browser-based LocalStorage? If so, I will get right on it. Otherwise, I don't see how it could hurt so would gladly accept a PR for adding it. Shouldn't be too hard.

**Comment by enriquepiatti** [comment]
I'm not sure, actually I'm trying to mimic the behaviour from chrome.storage
But that's ok, I can handle myself if is not correct for this project. Thanks !
