### ISSUE TITLE
events.EventEmitter.listenerCount is deprecated

### ISSUE THREAD

**Issue by enriquepiatti** [lmaccherone/node-localstorage#50]
https://nodejs.org/api/events.html#events_eventemitter_listenercount_emitter_eventname

**Comment by lmaccherone** [comment]
Can you elaborate a bit on what behavior you are observing and how the differs from what you expect or desire?

**Comment by lmaccherone** [comment]
Now I understand. I need to replace references to it with: https://nodejs.org/api/events.html#events_emitter_listenercount_eventname
