### ISSUE TITLE
get and set to not appear to be atomic

### ISSUE THREAD

**Issue by jcalfee** [lmaccherone/node-localstorage#6]
Please add a warning or fix (I prefer the later)...

http://www.w3.org/TR/webstorage/#the-storage-interface

"The setItem() and removeItem() methods must be atomic with respect to failure. In the case of failure, the method does nothing. That is, changes to the data storage area must either be successful, or the data storage area must not be changed at all."

**Comment by lmaccherone** [comment]
With the new atomic file operations, this is more atomic now. There still may be some issues if more than one file operation is necessary for the method, but the probability is greatly reduced now.
