### ISSUE TITLE
multiple Instances do not sync

### ISSUE THREAD

**Issue by NexusNull** [lmaccherone/node-localstorage#76]
I'm running multiple instances of node-localstorage in the same directory from different processes,
the problem is that when one instance creates an entry, this entry doesn't appear on the other instances.
That's why I would like to request some sort of syncing feature that updates the _keys periodically a function that can be called to sync _keys with the filesystem.

**Comment by lmaccherone** [comment]
I would gladly accept a pull request to achieve this. It seems like a good feature.

**Comment by NexusNull** [comment]
Oh, I just came back to this. I have it working on my branch, would probably only take a pull.
