### ISSUE TITLE
Please convert to plain old JS 🙏🙏

### ISSUE THREAD

**Issue by john-doherty** [lmaccherone/node-localstorage#84]
This is a great library, however, there are times I want to browse the code, for example, to figure out how to increase the quota. But I'm forced to learn/understand coffee script 😭 _(hurts so much!)_

**Comment by lmaccherone** [comment]
Quota question answered on the other issue. If I were ever to want to add significant features to a project, I would convert to plain old JS, but since the LocalStorage API is set there is no need, so I don't think it's worth it.
