### ISSUE TITLE
Proxy set handler does not return true on successful writes.

### ISSUE THREAD

**Issue by bmcbarron** [lmaccherone/node-localstorage#86]
If a Proxy `set` trap does not return `true`, then [a javascript implementation is allowed to throw](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/set#return_value). It seems that most implementations do not, but node 18.16.1 on arm7 does.

The return path on [line 78](https://github.com/lmaccherone/node-localstorage/blob/5498cdbd2e26819351eb505e71aae1feafdad81b/LocalStorage.coffee#L78) returns the value on the right side of the assignment. When the last local storage key is removed, this.length is set to 0, which is falsish, and so this branch throws.

The return path on line 80 delegates to [setItem](https://github.com/lmaccherone/node-localstorage/blob/5498cdbd2e26819351eb505e71aae1feafdad81b/LocalStorage.coffee#L156) which returns undefined on some paths, which is also falsish.

One way to fix would be to always have set return `true`.

**Comment by bmcbarron** [comment]
If you're ok with the `return true` solution, I can send a pull request. Although reviewing it might be more work than making the change yourself. Let me know what you'd like me to do. BTW - useful tool, thanks!

**Comment by lmaccherone** [comment]
@bmcbarron, I'm thinking about how best to implement this, but the conventions of this project are very out of date from my new normal. What do you think of me only supporting later versions of node.js going forward? For this project, I'm thinking of specifying node v13.2 or later so I can produce a single ESM formatted output. Thoughts?

**Comment by bmcbarron** [comment]
I use node v18 everywhere except Raspberry Pi, where I use node v16. So, I'm personally not concerned about that restriction. I've moved all of my code to ESM, so 👍 on that point, too.

**Comment by lmaccherone** [comment]
I did a quick release of v3.0.0 with your fix and a few other upgrades. While I have the hood up, I'm going to do a few more things so expect another version increment later today or tomorrow.
